### PR TITLE
TEXT-83: Deprecate CsvTranslators from from commons text in favor of Commons CSV

### PR DESCRIPTION
**Pull request by ameyjadiye**

### CODE REVIEW

**Comment by PascalSchumacher** [comment]
Thanks for the pull request. :+1: 

I think it is important to supply more information to users. It would be nice to add `@deprecated` javadoc tags to informs what can/should be used  instead and the version the deprecation occurred, e.g.:

https://github.com/apache/commons-lang/commit/844cd4298e46027ba1201df4eceb2dcaa5c1bb26

**Comment by PascalSchumacher** [comment]
Please include the jira issue in the commit comment, e.g.: `TEXT-83: Deprecate CsvTranslators from from commons text in favor of Commons CSV`

Thanks!

**Comment by ameyjadiye** [comment]
@garydgregory , I'm still in dilemma about this PR, thoughts ?

**Comment by chtompki** [comment]
If we're on the fence about this one, we could just put in considerable documentation discussing the use cases/limitations and offer `commons-csv` as an alternative or extension to the API with out the deprecation? Just a thought.

**Comment by garydgregory** [comment]
On Thu, Jun 1, 2017 at 10:16 AM, Rob Tompkins <notifications@github.com>
wrote:

> If we're on the fence about this one, we could just put in considerable
> documentation discussing the use cases/limitations and offer commons-csv
> as an alternative or extension to the API with out the deprecation? Just a
> thought.
>

I've not taken the time to think more on this one. But Javadoc without
deprecation is fine for now.

Gary

**Comment by ameyjadiye** [comment]
Hi @chtompki, do we expect anything more to be done here ? as per @garydgregory it looks good to be merged.

**Comment by chtompki** [comment]
Will look over this again tomorrow early.

**Pull request merged**
