### PR TITLE
Test: Improved testcase coverage for StrBuilder

### PR DESCRIPTION
**Pull request by ameyjadiye**
added some missing flows to testcases plus some nice formatting for easy understanding.

### CODE REVIEW

**Comment by PascalSchumacher** [comment]
Thanks!

Please separate the formatting fixes and the test additions into different commits.

Please stick to the existing code style for the new tests (no new line at the beginning and at the end of a test method; single new line between test methods).

**Comment by chtompki** [comment]
Agreed with Pascal here, just for semantics on commit history.

**Comment by ameyjadiye** [comment]
Fixed all the code as suggested, Thanks.

**Comment by PascalSchumacher** [comment]
Thanks for splitting the changes. :+1: 

But please also address the second part:

>Please stick to the existing code style for the new tests (no new line at the beginning and at the end of a test method; single new line between test methods).

Furthermore it would be very nice if you would clean up the history of the pull request by using `git rebase` once it is ready to merge.

After you commit the style fixes for the new tests you should be able to clean-up the history like this:

Use `git rebase -i head~5`. Choose to drop the first two commits (06e8b3dd06ee2f86490b2e94359d29d2fe04786c and 27e110b37f8f1e1cceee18ab614424f8a807a747). Squash d23bd1db8c0f21f62006b8cf0f41eb0588997a1e and the last commit. Afterwards use `push -f` to update the pull request.

After this there will be only two commits (one with the style changes and one with the new tests) and the commit history of commons-text will be pristine. :smile:

**Comment by ameyjadiye** [comment]
@PascalSchumacher This seems nice trick , but somehow didn't worked for me and ended up just pushing latest commit, can you try this once ? I have given you write access for exact this repository.

**Comment by PascalSchumacher** [comment]
Thanks. I was not as easy as I expected (I had to merge).

I followed these steps:

`git rebase -i head~5`

Edit the rebase-todo-to to contain:
```
drop 06e8b3d test: Improved testcase coverage for StrBuilder
drop  27e110b revert to master
pick d23bd1d Test: Improved testcase coverage for StrBuilder
squash 242ad5e Style fixes for StrBuilderTest
pick 31a5cd1 Fixed formatting for StrBuilder
```

Edit merge conflict.

`git rebase --continue`

Editmerge conflicts (nothing to do, just confirm merge was good).

`git rebase --continue`

`push -f`

Please remove my access to the repository. Thanks!

**Comment by ameyjadiye** [comment]
Cool, seems clean now :+1: thanks Pascal. Trick will be certainly beneficial in future to me 😉

**Comment by kinow** [comment]
Looking good! :+1:

**Comment by chtompki** [comment]
Thanks Amey.

**Pull request merged**
