### PR TITLE
TEXT-19 Add alphabet converter

### PR DESCRIPTION
**Pull request by eyala**
(as described in the [mailing list](http://mail-archives.apache.org/mod_mbox/commons-dev/201609.mbox/%3c289983494.3057706.1472720010277@mail.yahoo.com%3e))
(also, this pull request was originally sent to [commons-lang](https://github.com/apache/commons-lang/pull/188))

This is a utility class I wrote for converting from one alphabet to another - for example, from unicode to latin, without using some of the chars in latin. The usage looks like this:

Set<Character> originals; // a, b, c, d
Set<Character> encoding; // 0, 1, d
Set<Character> doNotEncode; // d

AlphabetConverter ac = AlphabetConverter.createConverter(originals, encoding, doNotEncode);

ac.encode("a"); // 00
ac.encode("b"); // 01
ac.encode("c"); // 0d
ac.encode("d"); // d
ac.encode("abcd"); // 00010dd

Of course,

x.equals(ac.decode(ac.encode(x)))

should always be true.

The implementation provided makes the encodings of fixed length, other than the "do not encode" chars, which remain as they are (length one).

In addition, in order to make it easier to preserve the encoding scheme, I've added a human-readable toString implementation, and a constructor that can recreate an AlphabetConverter from the encoding map, such that:

AlphabetConverter ac;

ac.equals(AlphabetConverter.createConverterFromMap(ac.getOriginalToEncoded())); // always should be true

### CODE REVIEW

**Comment by kinow** [comment]
I think I got the general idea, and indeed seems useful. So +1 for having it in [text].

There's some minor format-nit on regards to spaces, new lines, etc. But we can massage the code after merging.

Now I'm playing with the hashmaps for the original text and encoding alphabet. The AlphabetConverter doesn't seem to be thread-safe, as - I think - you can provide a map, modify it and influence the return value of the encode/decode methods.

Tried modifying the code to use unmodifiable maps, but then I realize that the static methods, which call the hidden private constructor, also alter the map passed to the constructor. Feel free to suggest other alternatives, or if you believe it is already thread-safe, or is easy to be made so.

My branch with the changes so far (tests failing) https://github.com/kinow/commons-text/tree/trying-thread-safety

**Comment by eyala** [comment]
If I understood you correctly, we can solve this by using a copy constructor on the factory method - it will be slightly wasteful for all the users who don't change the map, afterwards, but safer.
Eyal 

    On Wednesday, September 21, 2016 4:39 PM, Bruno P. Kinoshita <notifications@github.com> wrote:
 

 I think I got the general idea, and indeed seems useful. So +1 for having it in [text].There's some minor format-nit on regards to spaces, new lines, etc. But we can massage the code after merging.Now I'm playing with the hashmaps for the original text and encoding alphabet. The AlphabetConverter doesn't seem to be thread-safe, as - I think - you can provide a map, modify it and influence the return value of the encode/decode methods.Tried modifying the code to use unmodifiable maps, but then I realize that the static methods, which call the hidden private constructor, also alter the map passed to the constructor. Feel free to suggest other alternatives, or if you believe it is already thread-safe, or is easy to be made so.My branch with the changes so far (tests failing) https://github.com/kinow/commons-text/tree/trying-thread-safety—

**Comment by kinow** [comment]
What if we use arrays instead of sets? 

https://github.com/kinow/commons-text/blob/7b012b94deda08b0979e849ebdb7de8046639473/src/main/java/org/apache/commons/text/AlphabetConverter.java#L333

We would be guaranteeing thread-safety that way, and by also using an unmodifiable map in #createConverterFromMap.

There are other changes in the branch, such as:

- Javadocs for thread safety and since tag https://github.com/kinow/commons-text/blob/7b012b94deda08b0979e849ebdb7de8046639473/src/main/java/org/apache/commons/text/AlphabetConverter.java#L61
- Updating Javadocs to prevent Checkstyle errors https://github.com/kinow/commons-text/blob/7b012b94deda08b0979e849ebdb7de8046639473/src/main/java/org/apache/commons/text/AlphabetConverter.java#L418
- Adding a hashCode method too https://github.com/kinow/commons-text/blob/7b012b94deda08b0979e849ebdb7de8046639473/src/main/java/org/apache/commons/text/AlphabetConverter.java#L256
- Adding an if for null, in the decode method, so that encode(null) and decode(null) work as expected and explained in the Javadocs, and so that users don't get a NPE
- Constants for strings https://github.com/kinow/commons-text/blob/7b012b94deda08b0979e849ebdb7de8046639473/src/main/java/org/apache/commons/text/AlphabetConverter.java#L74

WDYT @eyala? Or we could go with the default design and add a thread-safety warning, stating that the class will be thread safe iff users use thread-safe collections or handle concurrency in their code.

**Comment by kinow** [comment]
One thing that I noticed is that checking out the pull request, and using a code similar to the one in the Javadocs, I get a different result.

```        
        Set<Character> originals = new HashSet<>(Arrays.asList(new Character[] {'a', 'b', 'c', 'd'}));
        Set<Character> encoding = new HashSet<>(Arrays.asList(new Character[] {'0', '1', 'd'}));
        Set<Character> doNotEncode = new HashSet<>(Arrays.asList(new Character[] {'d'}));
        
        AlphabetConverter ac = AlphabetConverter.createConverterFromChars(originals, encoding, doNotEncode);
        
        System.out.println(ac.encode("a"));
        System.out.println(ac.encode("b"));
        System.out.println(ac.encode("c"));
        System.out.println(ac.encode("d"));
        System.out.println(ac.encode("abcd"));
```

I get

```
10
1d
11
d
101d11d
```

Running the same test code against the branch with arrays instead of Sets, I get the same result.

Whereas the Javadocs seem to indicate that I should get:

```
00
01
0d
d
00010dd
```
Maybe I am missing something?

**Comment by eyala** [comment]
I want to start by saying how much I appreciate the review you're giving me - I'm glad you're catching all these things I've overlooked! I agree with almost all of the changes you've made.

The one thing I'm not sure about is the question of thread safety, and switching to arrays. I think returning an unmodifiable map in getOriginalToEncoded() is reasonable. But I prefer leaving the API to use Sets, because that way uniqueness is enforced in an easily-understandable way to users. If we want to change this to arrays, we should add a uniqueness check, and it will only be expressed in the javadoc.

In order to protect ourselves from modifications to the map passed to createConverterFromMap I think copying it is protection enough, with the price of some possibly unnecessary duplication. Maybe expressing it in javadocs is enough - I don't have a definite opinion.

As for the example in the javadocs - I get the same results that you do when I run the code - I don't remember now where I ran it to get these results (that I can't seem to replicate now). Maybe I created the Set (from the char array) in some other way, though I vaguely remember using AlphabetConverterTest.makeSet. Possibly the simplest thing to do would be to update the javadocs.

BTW, do we want to extract the interface and make it possible/easier to extend? Subclasses could implement their own logic for creating the mappings, and the encode/decode/createConverterFromMap methods would be reused.

**Comment by kinow** [comment]
>BTW, do we want to extract the interface and make it possible/easier to extend? Subclasses could implement their own logic for creating the mappings, and the encode/decode/createConverterFromMap methods would be reused.

Really the least I can do as you are willing to contribute such interesting piece of code, and took the time to write neat code, with tests :-)

> If we want to change this to arrays, we should add a uniqueness check, and it will only be expressed in the javadoc.

Good point. Otherwise the API could be misleading (or at least not really clear).

>In order to protect ourselves from modifications to the map passed to createConverterFromMap I think copying it is protection enough, with the price of some possibly unnecessary duplication. Maybe expressing it in javadocs is enough - I don't have a definite opinion.

Agreed. Let's go with the initial design, just using unmodifiableMap where possible, and using a local of the other collections.

>Possibly the simplest thing to do would be to update the javadocs.

+1 we can fix it after merging it, or you can update the pull request.

>BTW, do we want to extract the interface and make it possible/easier to extend? Subclasses could implement their own logic for creating the mappings, and the encode/decode/createConverterFromMap methods would be reused.

That'd be great if you could do it. I think I understand the AlphabetConverter now, but you would probably be the best person to write the initial interface :-)

Thanks!
Bruno

**Comment by eyala** [comment]
Hi Bruno,

I merged your changes, and added some more tests, although now I realize that I meant to change the javadocs and didn't push that. I meant to write that duplicates will be removed from the arrays, since that's what putting them into a Set will do (which means we don't actually need to do a uniqueness check).

I also think that declaring thread safety on the factory methods isn't technically true, although it would take a pathological use case to cause that. Theoretically you could launch many threads with the same array, and they could all try to modify it, and these modifications could occur before the static method _createConverter_ copies it, thus causing the situation where the set used doesn't reflect the state of the array when passed to the method.

I'm not sure whether extracting the AlphabetConverter interface is actually going to be useful, since only the encode/decode methods are truly "universal". If I leave _getEncodedCharLength()_ in the interface, it assumes that the encoding is of uniform length. If I leave _getOriginalToEncoded()_, it assumes an AlphabetConverter can be recreated from a Map, which is also implementation-specific.

(however, I feel like we're close to finishing this)( :-) )

**Comment by kinow** [comment]
Hi Eyal

>I also think that declaring thread safety on the factory methods isn't technically true, although it would take a pathological use case to cause that.

Oh, good point! You are right that there is still some risk even using arrays, my mistake.

>I'm not sure whether extracting the AlphabetConverter interface is actually going to be useful, since only the encode/decode methods are truly "universal". If I leave getEncodedCharLength() in the interface, it assumes that the encoding is of uniform length. If I leave getOriginalToEncoded(), it assumes an AlphabetConverter can be recreated from a Map, which is also implementation-specific.

I'm +0 for the interface. Happy to merge with or without it. I think the interface could be useful for users, plus the default implementation in the library. I thought we could go with just encode and decode. But if you think it's not a complete interface for an Alphabet Converter, then we can think about it later.

>(however, I feel like we're close to finishing this)( :-) )

Indeed! And twas fun to review this pull request, though a bit tricky to find settle on a good interface for thread-safety. Arrays or Sets, looks like we will have to inform users about the risk, and that they may need to ensure that they are not modifying the objects passed (or doing so with care). So now perhaps

- [ ] update Javadoc
- [ ] confirm we are happy with the current implementation regarding thread safety
- [ ] choose whether to have an interface or not
- [ ] merge it :)

I think only items 2 and 3 are pending. I'm Ok with the implementation the way it is for thread safety, given we warn users about risks. And +0 for the interface. Up to you know, then we merge it and update the JIRA ticket.

**Comment by eyala** [comment]
Ok. I've updated the javadoc (see if it's too terse), and added two more tests (I feel like all the exceptions thrown should have a test to make sure they're really thrown when applicable). No interface extraction - if another implementation is added (with different functionality or more efficient) we can split it then.

I think it's ready to be merged, unless you want me to squash the three commits into one for a cleaner git history.

**Comment by kinow** [comment]
That looks great Eyal.

I've merged your branch with master, squashing commits and updating the original message to include the "closes #NUMBER" so that - hopefully - our ASF infra integration automagically closes this pull request :)

The authorship of the commit should be attributed to your user, even though it's my user that pushed the commit. If you find I made a mistake on the commit tree, just let me know and I'll try to amend it.

`mvn clean test install` looks good. Also just had another look at the changes in gitk; everything looks OK. Pushing the changes to master, then will wait some minutes for the backend automation to run, and will update ticket and changes.xml.

Thanks a lot for your hard work Eyal.
Bruo

**Pull request closed without merging**
