### PR TITLE
TEXT-111

### PR DESCRIPTION
**Pull request by CAPS50**
Hi, this pull request fixes the issue that was reported in TEXT-111.

All other tests continue to pass.

### CODE REVIEW

**Comment by kinow** [comment]
Change looks good to me! No backward compatibility issues, Travis-CI is happy with the code changed, a test was included. And it looks like it fixes the bug. @PascalSchumacher would you like to have a look too before it gets merged? I saw that you commented in the issue some time ago. Cheers

**Comment by kinow** [comment]
Merged. Thanks @CAPS50 !

**Comment by CAPS50** [comment]
Thank you :) 👍

**Comment by CAPS50** [comment]
Hey @kinow, I was playing along with this method and found a possible infinite loop issue, and another combination where this fix is not enough.
I have a fix for those 2 cases, can I commit to this branch still, or shall I make a new pull request?

**Comment by kinow** [comment]
@CAPS50 it would have to be another pull request. And it would be great if you could create a JIRA for that pull request too, explaining the issue, as we include JIRA issues in the Changes Report for the component web site.

**Comment by CAPS50** [comment]
Thanks @kinow I have opened TEXT-152 and submitted the pull request

**Pull request merged**
