### PR TITLE
TEXT-106: Exception thrown in ExtendedMessageFormat using quotes with custom registry

### PR DESCRIPTION
**Pull request by kinow**
Created this pull request from the patch provided by Benoît Moreau in [TEXT-106](https://issues.apache.org/jira/browse/TEXT-106).

Thanks for your contribution Benoît!

Cheers
Bruno

### CODE REVIEW

**Comment by PascalSchumacher** [comment]
patch has some check-style violations, see: https://travis-ci.org/apache/commons-text/jobs/294087452

**Comment by ben12** [comment]
I have corrected my patch https://github.com/kinow/commons-text/pull/1

It is my first pull request, so if I have understand the worlflow, kinow must accept it to re-pull it here.

**Comment by kinow** [comment]
Already done @ben12! Hope first pull request of many :-)

**Comment by chtompki** [comment]
This feels like it should come in before I stage `commons-test-1.2`. Thoughts?

**Comment by PascalSchumacher** [comment]
+1

**Pull request merged**
