### PR TITLE
TEXT-152 - new tests and fix for infinite loop

### PR DESCRIPTION
**Pull request by CAPS50**
Hi, I have added a test that show shows the infinite loop, and the code that fixes it.

In order to make the test pass, and not only make the infinite loop stop happening, more changes were needed because the code for TEXT-111 did not fix the replacement of 0 length matches when we have multiple matches.

### CODE REVIEW

**Comment by garydgregory** [comment]
@CAPS50,

May you please update changes.xml?

Thank you,
Gary

**Comment by kinow** [comment]
@garydgregory I think the contributor goes under `due-to`. But sometimes new contributors add it as `dev`. And that way, it's tricky to know which value to put in `dev`. So it might be easier for a committer to add it when merging? At least that was my workflow so far

**Comment by CAPS50** [comment]
Thank you.

**Comment by CAPS50** [comment]
@kinow shall I change the changes.xml ? and if so should be the value of `dev` and `due-to`?

**Comment by garydgregory** [comment]
> @kinow shall I change the changes.xml ? and if so should be the value of `dev` and `due-to`?

IMO, you can leave `dev` empty and put your name in `due-to` (or you GitHub ID, Jira ID, whatever you prefer).

**Comment by CAPS50** [comment]
thanks, I did that.

**Comment by kinow** [comment]
Thanks @CAPS50 ! Merging now

**Pull request merged**
