### PR TITLE
TEXT-153: Make prefixSet a BitSet.

### PR DESCRIPTION
**Pull request by amirhadadi**

### CODE REVIEW

**Comment by garydgregory** [comment]
@amirhadadi,

Don't forget to update `changes.xml` with your name in the `due-to` field.

Gary

**Comment by kinow** [comment]
@garydgregory should we update CONTRIBUTING.md and/or the contributing section in our README adding a mention to the changes.xml file? (probably in the release plugin that generates those files)

**Comment by garydgregory** [comment]
That makes sense. The drawback is the confusion over dev and due-to. It
seems that in relation to github, dev should be the committer, an Apache
Committer and due-to the GitHub PR Author.

Gary

**Comment by amirhadadi** [comment]
@garydgregory updated changes.xml.

**Pull request merged**
