### PR TITLE
partial automated migration to assertj

### PR DESCRIPTION
**Pull request by PascalSchumacher**
Migrated using a modified version of https://github.com/joel-costigliola/assertj-core/blob/master/src/main/scripts/convert-junit-assertions-to-assertj.sh

I reverted changes where the automated migration did not work to minimize effort for this prototype.

The script use only the most basic assertj assertions, so the full power is not evident.

### CODE REVIEW

**Comment by britter** [comment]
Cool! Have missed the discussion about introducing this for Text. I like it.

**Comment by PascalSchumacher** [comment]
>Cool! Have missed the discussion about introducing this for Text. I like it.

These was no discussion yet. I just thought I do a quick prototype with a component after the general discussion of assertj.

**Comment by britter** [comment]
Good idea. It's always better to discuss with some acutal code examples at hands.

**Comment by kinow** [comment]
Looks good to me. Given [text] is already on Java 8, I believe it's a good candidate to start using assertj.

>The script use only the most basic assertj assertions, so the full power is not evident.

Indeed. But I like this approach. We introduce assertj, migrate the old assertions, and only then we start replacing/simplifying parts of the tests. And new text code can also be written with assertj.

**Comment by kinow** [comment]
I thought we were using Java 8, but [text] is actually using Java 7. I thought there was some discussion around the minimum requirement for the latest version of assertj being Java 8? So I assume it's safe to start with 2.8.0 now, and bump up to 3.8.0 later when we upgrade do Java 8?

**Comment by PascalSchumacher** [comment]
Sure. AssertJ 2.x for java 7 and 3.x for java 8 have been developed in parallel for a few years (and currently still are). Java 7 compatible changes are done in 2.x and then merged into 3.x, so 3.x is essentially 2.x plus support for lambdas, predicates and java 8 classes. Migrating for AssertJ 2.x to 3.x is easy, I did it for multiple projects without problems.

**Comment by PascalSchumacher** [comment]
@chtompki What do you think?

**Pull request closed without merging**
