### PR TITLE
TEXT-36: Dependency on "Commons RNG"

### PR DESCRIPTION
**Pull request by RayDeCampo**
Create functional interface to provide randomness for RandomStringGenerator.

Implements one solution to the issue of dependency on Commons RNG as discussed in issue TEXT-36.

### CODE REVIEW

**Comment by chtompki** [comment]
Cool. Glad to see this open. It'll have to hang out for a little while because I want to get the `1.0` release out the door before doing this work. I think I'll try to get that release together in the next week to two weeks.

Regardless of the timing, thanks a ton for hopping in here and working on this.

**Comment by PascalSchumacher** [comment]
@chtompki As text 1.0 was released, what do you think about merging this?

**Comment by PascalSchumacher** [comment]
Merged. Thanks! :

**Comment by chtompki** [comment]
+1

**Pull request closed without merging**
