### PR TITLE
TEXT-82 : Reverting back WordUtils to master as per Jira TEXT-82

### PR DESCRIPTION
**Pull request by ameyjadiye**

### CODE REVIEW

**Comment by ameyjadiye** [comment]
Hi @chtompki , I see some check-style errors, code is taken from branch TEXT-55 as is. 
shall i resolve them and push here another commit ?

**Comment by chtompki** [comment]
Your call. I've been playing around with them too. The only one that's a tad annoying is the MagicNumber violation. I never can tell whether it's better to ignore those or actually try to solve them.

**Comment by ameyjadiye** [comment]
@chtompki , @kinow , there are some method signatures longer than 120 words, I have option to just cut descriptive variable names like **length** to *len*, **wrap** to *wrp*, **words** to *wrd* etc ... but in that way we are loosing the purpose of having descriptive code where ```code says it all``` and dont need any documentation to read again, please suggest.

**Comment by chtompki** [comment]
Oh I just add new lines in the file after the commas. Eg. 

```java
    public static String wrap(final String str,
                              int wrapLength,
                              String newLineStr,
                              final boolean wrapLongWords,
                              String wrapOn) {
```

**Comment by chtompki** [comment]
I think it's just complaining about line length generally, not that the signature's too long.

**Comment by ameyjadiye** [comment]
Yeah, putting new line after each param looks ugly thats why i was trying to cut param names and keeping them in single line, if this works in commons community i'm good with it.

**Comment by chtompki** [comment]
I've got to step away from my machine for a bit but I'll try to tackle this in the next 6 hours or so.

**Pull request merged**
