### PR TITLE
TEXT-197 - Replace statement lambda with expression lambda

### PR DESCRIPTION
**Pull request by arturobernalg**

### CODE REVIEW

**Review by kinow — CHANGES_REQUESTED** [review]
Can you take a look at the Java 8 failures, please @arturobernalg ?

```
 Error:  Failures: 
Error:    DnsStringLookupTest.testCanonicalNameFromHostAddress:48 expected: <10.1.0.197> but was: <fv-az296-124.internal.cloudapp.net>
```

**Comment by arturobernalg** [comment]
> Can you take a look at the Java 8 failures, please @arturobernalg ?
> 
> ```
>  Error:  Failures: 
> Error:    DnsStringLookupTest.testCanonicalNameFromHostAddress:48 expected: <10.1.0.197> but was: <fv-az296-124.internal.cloudapp.net>
> ```

Hi @kinow 
It's quite strange. especially because InetAddress is a native java object. Can we re launch the job? 
Seems there is no change in this clase. Weird
TY

**Comment by kinow** [comment]
> 
> 
> > Can you take a look at the Java 8 failures, please @arturobernalg ?
> > ```
> >  Error:  Failures: 
> > Error:    DnsStringLookupTest.testCanonicalNameFromHostAddress:48 expected: <10.1.0.197> but was: <fv-az296-124.internal.cloudapp.net>
> > ```
> 
> Hi @kinow
> It's quite strange. especially because InetAddress is a native java object. Can we re launch the job?
> Seems there is no change in this clase. Weird
> TY

I haven't had time to look more into the error, sorry. Will try to review it again tomorrow. For now I've re-triggered the jobs 👍

**Comment by arturobernalg** [comment]
> > > Can you take a look at the Java 8 failures, please @arturobernalg ?
> > > ```
> > >  Error:  Failures: 
> > > Error:    DnsStringLookupTest.testCanonicalNameFromHostAddress:48 expected: <10.1.0.197> but was: <fv-az296-124.internal.cloudapp.net>
> > > ```
> > 
> > 
> > Hi @kinow
> > It's quite strange. especially because InetAddress is a native java object. Can we re launch the job?
> > Seems there is no change in this clase. Weird
> > TY
> 
> I haven't had time to look more into the error, sorry. Will try to review it again tomorrow. For now I've re-triggered the jobs 👍

It's weird, now it's worked and have finish OK

**Review by kinow — APPROVED** [review]
Build worked fine for me. Travis is failing due to checkstyle. Looks like it's not running in GH actions. Not related to this issue. LGTM, thanks @arturobernalg

**Pull request closed without merging**
