### PR TITLE
Fixed TEXT-234

### PR DESCRIPTION
**Pull request by TobiasKiecker**
fixed documentation for setNewLineText, getNewLineText and appendNewLine in both StrBuilder and TextStringBuilder to better reflect their behavior

### CODE REVIEW

**Comment by garydgregory** [comment]
Hello @TobiasKiecker 
Thank you for your PR.
Please see git master where I updated the Javadoc throughout for this topic.
The wording in some of the changes in this PR felt awkward (to me).

**Comment by TobiasKiecker** [comment]
Looks fine to me, but you just updated StrBuilder (the deprecated class) while TextStringBuilder, which in this aspect is a direct copy, remains unchanged

**Comment by garydgregory** [comment]
> Looks fine to me, but you just updated StrBuilder (the deprecated class) while TextStringBuilder, which in this aspect is a direct copy, remains unchanged

Feel free to provide a PR with changes in the same style for other classes 😉

**Comment by TobiasKiecker** [comment]
I will do that

**Pull request closed without merging**
