### PR TITLE
TEXT-2  Jaccard Index and Jaccard Distance

### PR DESCRIPTION
**Pull request by drajakumar**

### CODE REVIEW

**Comment by chtompki** [comment]
Can you add your name in the pom.xml and a line in src/changes/changes.xml for the change? I think that would complete the work.

**Comment by drajakumar** [comment]
@chtompki now added the entries in .xml file, looks like there is a conflict for merging the changes. Can you let me know any action from my side in this regard.
Thank you!

**Comment by chtompki** [comment]
The conflict isn't really an issue, I can sort that out. I'll give things another read and then pull it in.

**Comment by chtompki** [comment]
Don, I'm not sure if I've said this, but thanks a ton for the contribution.

**Comment by drajakumar** [comment]
Thank you Rob!

**Pull request merged**
