### PR TITLE
Initial implementation of random string generation (TEXT-34).

### PR DESCRIPTION
**Pull request by dmjones500**
Firstly, I'm a bit unpracticed with pull requests vs. just committing to the master branch, so apologies if this goes wrong. However I thought this was a good way to get some feedback.

I've written an implementation for random string generation, using a builder pattern. Units tests included.

Thoughts welcome! If everyone is happy, I'll commit this.

### CODE REVIEW

**Comment by dmjones500** [comment]
Please assume I'll alter changes.xml as well.

**Comment by PascalSchumacher** [comment]
I did not dive into the implementation, but the API looks nice. 👍 

I guess it would be nice to allow generating strings between an min and max length, but support for this can also be added later on.

**Comment by dmjones500** [comment]
Screwed up trying to merge the pull request, but this is now committed to trunk.

**Comment by chtompki** [comment]
Just an fyi on how to pull it in based on the following PR. I'll show from the last push you make up to the repo from `TEXT-34`, where the commands you enter are lines beginning with a `$`. Also, I'm assuming that your git repo is handled "origin" while the ASF repo is handled "upstream." Oh, one other thing, the outputs to the git commands I kinda lifted from what I just ran without running the `git push upstream master`.
```bash
$ git status
  On branch TEXT-34
  nothing to commit, working directory clean
$ git push origin TEXT-34
  Counting objects: 283, done.
  Delta compression using up to 8 threads.
  Compressing objects: 100% (133/133), done.
  Writing objects: 100% (283/283), 43.78 KiB | 0 bytes/s, done.
  Total 283 (delta 131), reused 144 (delta 60)
$ git checkout master
  Switched to branch 'master'
  Your branch is ahead of 'origin/master' by 20 commits.
    (use "git push" to publish your local commits)
$ git pull upstream master
  remote: Counting objects: 181, done.
  remote: Compressing objects: 100% (24/24), done.
  remote: Total 42 (delta 12), reused 0 (delta 0)
  Unpacking objects: 100% (42/42), done.
  From https://git-wip-us.apache.org/repos/asf/commons-text
   * branch            master     -> FETCH_HEAD
     0e09bb8..1204090  master     -> upstream/master
  Updating 0e09bb8..1204090
  Fast-forward
   src/changes/changes.xml                                              |   2 ++
   src/main/java/org/apache/commons/text/RandomStringBuilder.java       | 353   ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
   src/main/java/org/apache/commons/text/StringEscapeUtils.java         |   8 ++---
   src/main/java/org/apache/commons/text/similarity/CosineDistance.java |  12 +++++--
   src/test/java/org/apache/commons/text/RandomStringBuilderTest.java   | 235   ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
   5 files changed, 603 insertions(+), 7 deletions(-)
   create mode 100644 src/main/java/org/apache/commons/text/RandomStringBuilder.java
   create mode 100644 src/test/java/org/apache/commons/text/RandomStringBuilderTest.java
$ git reset --hard upstream/master
  HEAD is now at 1204090 <<<<the_last_commit_message_from_master_gets_outputted_here>>>>
$ git pull origin TEXT-34
From github.com: dmjones500/commons-text
   * branch            TEXT-34    -> FETCH_HEAD
  Updating 1204090..913f9cf
  Fast-forward
   src/main/java/org/apache/commons/text/similarity/LongestCommonSubsequence.java     | 160 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
   src/test/java/org/apache/commons/text/similarity/LongestCommonSubsequenceTest.java |  36 ++++++++++++++++++++++++++++++++++++
   2 files changed, 196 insertions(+)
   create mode 100644 src/main/java/org/apache/commons/text/similarity/LongestCommonSubsequence.java
   create mode 100644 src/test/java/org/apache/commons/text/similarity/LongestCommonSubsequenceTest.java
$ git push upstream master
```

**Comment by chtompki** [comment]
Oh, regardless of all of that, thanks a ton for the contribution. Cheers.

**Comment by dmjones500** [comment]
Thanks for showing me how to do that :-)

**Pull request closed without merging**
