### PR TITLE
changed graalvm.version to 23.0.3, built successfully, tests were suc…

### PR DESCRIPTION
**Pull request by arashmpr**
This change resolves #490 by replacing the old versions of graalvm to 23.0.3.

### CODE REVIEW

**Review by garydgregory — COMMENTED** [review]
How is that going to work on Java 8?

**Comment by arashmpr** [comment]
is it okay to change the java version to 21 or 22?

**Comment by garydgregory** [comment]
> > How is that going to work on Java 8?
> 
> is it okay to change the java version to 21 or 22?

Absolutely not.

**Comment by garydgregory** [comment]
Closing: The proper solution is now in git master.

**Pull request closed without merging**
