### PR TITLE
TEXT-74 Introduced new StrSubstitutor attribute to disable recursive substitution

### PR DESCRIPTION
**Pull request by sermojohn**

### CODE REVIEW

**Comment by PascalSchumacher** [comment]
Thanks for the pull request!

It would be nice if you could fix the checkstyle violations. See https://travis-ci.org/apache/commons-text/jobs/284821493 for details or run "mvn checkstyle:check" locally.

Thanks!

**Comment by sermojohn** [comment]
Thank you for the notice!

**Comment by PascalSchumacher** [comment]
Thanks!

Imho this pull request is good to merge. Only thing that is missing are `@since 1.2` tags in the javadoc of the new methods.

@chtompki What do you think?

**Comment by chtompki** [comment]
Seems reasonable to me.

**Comment by chtompki** [comment]
Do we want it to be off by default?

**Comment by sermojohn** [comment]
For backwards compatibility, it needs to be off by default, so recursive substitution applies by default.

**Comment by arend-von-reinersdorff** [comment]
@sermojohn Great, thanks :-)

**Pull request merged**
