### PR TITLE
TEXT-24

### PR DESCRIPTION
**Pull request by chtompki**
@kinow, @britter - You guys have any issues with putting this in place?

Resolves:
https://issues.apache.org/jira/browse/TEXT-24

### CODE REVIEW

**Comment by chtompki** [comment]
Potential coverage report:
https://coveralls.io/github/chtompki/commons-text
Potential build:
https://travis-ci.org/chtompki/commons-text

**Comment by kinow** [comment]
@chtompki looks great! Go for it :-)

**Comment by britter** [comment]
@chtompki remember, that you need to file an issue for INFRA to set up travis and coveralls jobs. Thank you!

**Comment by kinow** [comment]
He already did it @britter :-) INFRA-12862

**Pull request merged**
