### PR TITLE
TEXT-88: Fixed issue with empty delimiters array with capitalizeFully

### PR DESCRIPTION
**Pull request by ameyjadiye**

### CODE REVIEW

**Comment by arunvinudss** [comment]
@ameyjadiye The agreed upon fix as of now should be:

WordUtils.capitalizeFully("i am fine", new char[]{})  --> I am fine

We shouldn't take space as the delimiter as the user explicitly passes an empty array for delimiter . Anyways we are still discussing on that and I guess you can make the required changes once we have an agreement on this .

**Comment by ameyjadiye** [comment]
I think we are good to merge this as per discussion here [TEXT-88](https://issues.apache.org/jira/browse/TEXT-88)

**Comment by chtompki** [comment]
Should we add to `public static boolean isDelimiter(final char ch, final char[] delimiters)` or `isDelimiter` generally, documentation stating that if an empty array is passed in we always return false?

I'm torn on this. What are your thoughts @ameyjadiye?

**Comment by ameyjadiye** [comment]
```isDelimiter``` is simply the method to identify if codePoint or char is present in given second parameter which is array. ofcource if array is empty it means first param is not present in array and should return false, I think overall behaviour of ```capitalizeFully```  is correct now.

**Pull request merged**
