### PR TITLE
removed unused variable

### PR DESCRIPTION
**Pull request by orionlibs**

### CODE REVIEW

**Review by kinow — CHANGES_REQUESTED** [review]
To remove public variables, even unused, we must wait for a major change.

```bash
Error:  Failed to execute goal com.github.siom79.japicmp:japicmp-maven-plugin:0.17.2:cmp (default-cli) on project commons-text: There is at least one incompatibility: org.apache.commons.text.RandomStringGenerator$Builder.DEFAULT_LENGTH:FIELD_REMOVED -> [Help 1]
Error:  
Error:  To see the full stack trace of the errors, re-run Maven with the -e switch.
Error:  Re-run Maven using the -X switch to enable full debug logging.
Error:  
Error:  For more information about the errors and possible solutions, please read the following articles:
Error:  [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
Error: Process completed with exit code 1.
```

**Comment by orionlibs** [comment]
Oh. I see. Sorry

**Comment by garydgregory** [comment]
> To remove public variables, even unused, we must wait for a major change.
> 
> ```shell
> Error:  Failed to execute goal com.github.siom79.japicmp:japicmp-maven-plugin:0.17.2:cmp (default-cli) on project commons-text: There is at least one incompatibility: org.apache.commons.text.RandomStringGenerator$Builder.DEFAULT_LENGTH:FIELD_REMOVED -> [Help 1]
> Error:  
> Error:  To see the full stack trace of the errors, re-run Maven with the -e switch.
> Error:  Re-run Maven using the -X switch to enable full debug logging.
> Error:  
> Error:  For more information about the errors and possible solutions, please read the following articles:
> Error:  [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
> Error: Process completed with exit code 1.
> ```

@orionlibs 
You can check for these types of errors yourself before pushing commits by running a local build (`mvn`)

**Comment by orionlibs** [comment]
I will do it from now on. Thank you and sorry (at the same time)

**Pull request closed without merging**
