### PR TITLE
Upgrade to JUnit 5.1

### PR DESCRIPTION
**Pull request by PascalSchumacher**

### CODE REVIEW

**Comment by PascalSchumacher** [comment]
The only problem I encountered was that I had to delete the existing JUnit run configurations for commons-text (I'm using Eclipse Oxygen.3 and it does not seem to be able to update a run configuration from JUnit 4 to JUnit 5).

**Comment by PascalSchumacher** [comment]
JUnit 5 should work with any Eclipse Version released during the last year (as long as you delete existing run configurations for the project).

@garydgregory Can you give running this a try? I would like to merge it. Thanks!

**Comment by kinow** [comment]
Tested the master branch first, and everything obviously worked. Then switched to this branch, and got an error message, then Eclipse opened the run configuration.

Followed @PascalSchumacher 's suggestion, removed the project JUnit run configurations, then re-run the class, and everything worked with no issues.

Tested a class, a method, and the entire project, by right clicking each of these, then Run As -> JUnit Test (i.e. Eclipse also recognized the files as JUnit tests).

Also put a breakpoint in some random method, then Debug As -> JUnit Test, and it worked as expected too.

Looks good to me. Might be a good idea to wait for @garydgregory 's feedback as I have very little experience with JUnit 5 for now, besides reading slides/docs/etc.

**Comment by kinow** [comment]
screenshot_2018-04-08_22-34-52

Screenshot with Eclipse version, and sample output (looks exactly like the output with JUnit 4).

**Comment by garydgregory** [comment]
Comitted! :-) Works for me as well in Eclipse 4.7.3.

**Comment by PascalSchumacher** [comment]
Great!

@kinow Thanks in-depth check!

**Pull request closed without merging**
