### PR TITLE
TEXT-97: RandomStringGenerator able to pass multiple ranges to .withinRange()

### PR DESCRIPTION
**Pull request by ameyjadiye**
*.withinRange()* now able to accept multiple ranges.

Ex.
```
final char [][] pairs = {{'a','z'},{'0','9'}};
RandomStringGenerator generator = new RandomStringGenerator.Builder().withinRange(pairs).build();
```

### CODE REVIEW

**Comment by ameyjadiye** [comment]
@chtompki , @PascalSchumacher , can you please express your opinion on this , please check JIRA for detail discussion.

**Comment by chtompki** [comment]
Sure...I'll try to look at this in the coming day or so.

**Comment by jbduncan** [comment]
@ameyjadiye I don't know if there's a convention in Apache Commons for preferring `new X.Builder()` over static factory methods like `X.builder()`, but if there isn't, then I would encourage changing the API so that instead of `new RandomStringGenerator.Builder()`, one can write the shorter and arguably more readable `RandomStringGenerator.builder()`.

**Comment by chtompki** [comment]
@jbduncan has a point here, but the code here does conform to the style of the existing code. So, I'd lean more towards the changes @ameyjadiye is proposing mainly because to re-work the code into a static `builder()` method pattern would require changes that would necessitate a major version change. We could, though, revisit this in the 2.X version if you with @jbduncan. Thoughts?

**Comment by jbduncan** [comment]
Revisiting this in 2.x sounds good to me!

The only other thought I have is that I think this should go up as a new issue on Apache JIRA if it hasn't already.

Other than that, everything LGTM.

**Comment by ameyjadiye** [comment]
Yeah, will see if we can simplify API in 2.x .
I need opinion on the method I have given in this PR, According to me it's good addition to existing API but go through JIRA discussion once.

**Comment by ameyjadiye** [comment]
@chtompki , If possible can you review and accept this ? I need this for TEXT-101.

**Comment by chtompki** [comment]
Are we ready to do a change that would necessitate a 2.X?

**Comment by chtompki** [comment]
Pardon...I don't see why this would necessitate a 2.X. Let me re-read.

**Comment by ameyjadiye** [comment]
@chtompki , I'm sorry for such short note, 2.x was for making .builder() static, PR seems ok for accepting in 1.2 release, you might want to go though jira as well.

**Pull request merged**
